const fs = require('fs')
const path = require('path')

const pkg = require(path.join(__dirname, '..', 'package.json'))
const target = path.join(__dirname, '..', 'src', 'version.js')
const content = `// Auto-generated by scripts/sync-version.js — do not edit by hand.\nexport const APP_VERSION = '${pkg.version}'\n`

fs.writeFileSync(target, content)
console.log(`Synced src/version.js to ${pkg.version}`)
